---
title: "Live async, live happy"
author: "VB"
date: "2024-07-29"
description: "Why I skip meetings, ignore calls, and prefer written communication. Async is the way."
categories: [async]
---

Why I don’t take calls and take ages to respond?

I often get my butt kicked for not responding to acquaintances and colleagues on time. I also get the stink eye for refusing to do meetings, phone/ zoom calls, and everything that comes with them.

To be honest, a one-hour physical meeting can be a 30-minute virtual meeting, a 30-minute virtual meeting can be a 10-minute phone call, and a 10-minute phone call can be a 2-minute email.

I prefer written communication. It’s documented, clear, and doesn’t require me to break my focus.

**But why avoid meetings in the first place? Isn’t face-to-face interaction better?**

I have the attention span of a peanut. It often takes me ages to find inspiration. Once I find that inspiration, I like capitalising on it as much as possible. Given how fickle my mind is I tend to aggressively preserve my “inspired time”.

While face-to-face interactions “may” be better. They do result in an absurd amount of cognitive load. 

So why make life difficult for both you and me? Async rules!

**What about virtual meetings? They are a good proxy for in-person meetings and don’t often require as much time.**

True-ish, but if I know I have a meeting on a particular day, I’d constantly be stressing out about it. Irrespective of the contents of the meeting, I’d be consumed by it and have a sub-optimal experience. 

**How do I reach you?**

Email me at Vaibhavs10[at]gmail[dot]com or drop a line on twitter [@reach_vb](https://twitter.com/reach_vb) 🤗

*Live async, live happy!*