---
title: "Now"
---

What am I focused on at this point in life?

Updated 30th September 2024, from Stuttgart, DE.

# 📚 Research & Work
---

Work has been hectic but enjoyable. I have been forunate to collaborate with some of the brightest minds in the field at the moment.
I have been spending more time understanding the intrecacies and implications of running ML on the edge and deployment.

I haven't been able to find a single continuous block of time to put my head down and do good old research or even read papers in a long while. Still not sure what's the best way, but I'll figure it out.

It's been quite surreal to see some of the projects that I worked on be out and about in the wild making real-life impact. Time to double down on what gets the blood pumping.

# 🙌 Volunteering
---

I stepped back from EuroPython organisation and am looking forward to complete my tenure this year. Truth be told, there was a lot of friction (mostly because of me) this year. I'm happy to see the chapter close with my best friends in the coming weeks.
The past 1.5 years have been quite chaotic, moving countries, building a home, settling in has all been incredibly taxing. I'm looking forward to having less things on my plate and focus on getting better.

I have been dedicating extra chunk of time working on building Proof of Concepts/ examples/ tutorials on using better, more powerful AI models at the touch of your computer.

# 🧠 Mental health
---

Sounds unbelievable but I have been quite stable (mentally) in the recent times. I do owe a lot of this to Sof. I am quite lucky to have her in my life, she just knows how to comfort me and ndges me with the right prompts. She's a good prompt engineer ;)

My physical health on the other hand has been on a decline, I fall sick at the drop of the hat and it's not fun loading up on medicines every other week.
Although, I did recently get back into running and picked up longboarding, both are fun and good ways to keep the blood flowing. With a little bit of consistency I might get better afterall.

Note: I still suck at keeping in touch with people, hoping I auto-magically fix it soon.

# 🏡 “Home”
---

Spent the last couple days in Stuttgart, reliving the old days, meeting friends and people I spent considerable amount of last 4 years with. I find myself thinking/ fascinating about where should I move next - each country, city and street has pros and cons.
But, spending time figuring out what is it that I like in a city is fun. The introspection and discussion around this would make for a blogpost on its own - looking forward to writing it.

I do quite enjoy where I live currently - It's just nothing beats being able to walk in a forest, hill all less than one hour by public transport from you (looking at you Stuttgart).

# ✈️ Travel & Plans going forward
---

When this year started both Sof and I decided to reduce travel to bare minimum. I don't know where this got out of hand, but June was the only month where we did not travel anywhere, looking forward it looks like this would be the case for the whole year.

Gearing up for some intense travel till the end of the year! 😅
