---
title: "30"
author: "VB"
date: "2024-08-05"
categories: [life, reflections]
---

- Some beliefs that shaped the last decade:
- you’re capable of much more than you can imagine, every now and then set an immeasurable goal
- your only competition is you, everyone else is a distraction - you’ve only got a lifetime to get better
- strive deliver value in good faith, when in doubt, walk away
- don’t treat money as a taboo, money attracts money, it is never obvious in the moment; but in hindsight
- your choice in partner is the most important, spend time on it; make sure there’s alignment - this is not something you can “wing it”
- people are not inherently bad, but some can still cause more harm than good - mute/ block repeat
- keep the curiosity alive, it’s the only true antidote to boredom
- higher high would certainly lead to lower lows; you never recognise either before they hit you
- be receptive to feedback, specially critical; be wary of good feedback - it’s sneaky
- health is wealth; this is a fact - internalise it, practice it, make it a big part of your life
